name: my_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.1.0
  file: ^5.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  #https://github.com/luanpotter/audioplayers
  audioplayers: ^0.14.0
  #https://github: com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  #https://github.com/best-flutter/flutter_page_indicator
  flutter_page_indicator: ^0.0.3
  #https://github.com/flutter/plugins/tree/master/packages/video_player
  video_player:
  # https://github:com/brianegan/chewie:
  chewie: ^0.9.5
  #https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  #https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.9
  # https://github:com/fluttercandies/extended_text_field:
  extended_text_field: ^0.5.0
  url_launcher: 5.3.0
  # https://github: com/fluttercandies/extended_nested_scroll_view:
  extended_nested_scroll_view: ^0.4.0
  # https://github.com/theyakka/fluro
  fluro: 1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_screenutil: ^0.5.2
  dio: 3.0.9
  fluttertoast: ^3.1.0
  shared_preferences: ^0.5.3
  synchronized: ^2.1.0
  event_bus: ^1.0.1

  #https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.6.1+4
  #https://github.com/adee42/flutter_keyboard_visibility
  keyboard_visibility: ^0.5.6


  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler:   '^3.0.0'


  #https://github.com/Daegalus/dart-uuid
  uuid: 2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: HotSearch
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
